# Hardcoded curated dictionary of Top 300 highly liquid US stocks and Top 150 EU stocks.

TICKER_MAPPING = {
    "GLW": "Corning Incorporated",
    "MGM": "MGM Resorts International",
    "ROP": "Roper Technologies, Inc.",
    "SNOW": "Snowflake Inc.",
    "JKHY": "Jack Henry & Associates, Inc.",
    "PNC": "The PNC Financial Services Group, Inc.",
    "CSCO": "Cisco Systems, Inc.",
    "AMAT": "Applied Materials, Inc.",
    "KLAC": "KLA Corporation",
    "MAR": "Marriott International, Inc.",
    "TMO": "Thermo Fisher Scientific Inc.",
    "PG": "The Procter & Gamble Company",
    "EXC": "Exelon Corporation",
    "SYY": "Sysco Corporation",
    "GOOG": "Alphabet Inc.",
    "LVS": "Las Vegas Sands Corp.",
    "NSC": "Norfolk Southern Corporation",
    "MDT": "Medtronic plc",
    "NVDA": "NVIDIA Corporation",
    "BKNG": "Booking Holdings Inc.",
    "WM": "Waste Management, Inc.",
    "LDOS": "Leidos Holdings, Inc.",
    "AXP": "American Express Company",
    "UNH": "UnitedHealth Group Incorporated",
    "EW": "Edwards Lifesciences Corporation",
    "XYL": "Xylem Inc.",
    "ALB": "Albemarle Corporation",
    "VRTX": "Vertex Pharmaceuticals Incorporated",
    "WCC": "WESCO International, Inc.",
    "CE": "Celanese Corporation",
    "TRMB": "Trimble Inc.",
    "IFF": "International Flavors & Fragrances Inc.",
    "SCHW": "The Charles Schwab Corporation",
    "GOOGL": "Alphabet Inc.",
    "ODFL": "Old Dominion Freight Line, Inc.",
    "PEG": "Public Service Enterprise Group Incorporated",
    "FIS": "Fidelity National Information Services, Inc.",
    "YUM": "Yum! Brands, Inc.",
    "ROK": "Rockwell Automation, Inc.",
    "BRK-B": "Berkshire Hathaway Inc.",
    "PKG": "Packaging Corporation of America",
    "BIO": "Bio-Rad Laboratories, Inc.",
    "EOG": "EOG Resources, Inc.",
    "PSX": "Phillips 66",
    "META": "Meta Platforms, Inc.",
    "INCY": "Incyte Corporation",
    "GS": "The Goldman Sachs Group, Inc.",
    "UBER": "Uber Technologies, Inc.",
    "DLTR": "Dollar Tree, Inc.",
    "MCK": "McKesson Corporation",
    "CMG": "Chipotle Mexican Grill, Inc.",
    "NKE": "NIKE, Inc.",
    "TT": "Trane Technologies plc",
    "CVS": "CVS Health Corporation",
    "ITW": "Illinois Tool Works Inc.",
    "PLD": "Prologis, Inc.",
    "MO": "Altria Group, Inc.",
    "DDOG": "Datadog, Inc.",
    "ISRG": "Intuitive Surgical, Inc.",
    "TEL": "TE Connectivity plc",
    "PSA": "Public Storage",
    "AMZN": "Amazon.com, Inc.",
    "RTX": "RTX Corporation",
    "PCAR": "PACCAR Inc",
    "PCG": "PG&E Corporation",
    "SPGI": "S&P Global Inc.",
    "ABNB": "Airbnb, Inc.",
    "AAPL": "Apple Inc.",
    "PEP": "PepsiCo, Inc.",
    "KO": "The Coca-Cola Company",
    "APD": "Air Products and Chemicals, Inc.",
    "BLK": "BlackRock, Inc.",
    "TSLA": "Tesla, Inc.",
    "MCHP": "Microchip Technology Incorporated",
    "SAIC": "Science Applications International Corporation",
    "FTNT": "Fortinet, Inc.",
    "MCO": "Moodys Corporation",
    "AMD": "Advanced Micro Devices, Inc.",
    "SYK": "Stryker Corporation",
    "SBUX": "Starbucks Corporation",
    "CCI": "Crown Castle Inc.",
    "RSG": "Republic Services, Inc.",
    "CEG": "Constellation Energy Corporation",
    "F": "Ford Motor Company",
    "NXPI": "NXP Semiconductors N.V.",
    "LIN": "Linde plc",
    "IDXX": "IDEXX Laboratories, Inc.",
    "AMGN": "Amgen Inc.",
    "CTAS": "Cintas Corporation",
    "NUE": "Nucor Corporation",
    "IP": "International Paper Company",
    "LLY": "Eli Lilly and Company",
    "BIIB": "Biogen Inc.",
    "SRE": "Sempra",
    "HON": "Honeywell International Inc.",
    "DUK": "Duke Energy Corporation",
    "CSGP": "CoStar Group, Inc.",
    "BR": "Broadridge Financial Solutions, Inc.",
    "ECL": "Ecolab Inc.",
    "CDNS": "Cadence Design Systems, Inc.",
    "RMD": "ResMed Inc.",
    "LOW": "Lowes Companies, Inc.",
    "MSFT": "Microsoft Corporation",
    "MPC": "Marathon Petroleum Corporation",
    "MOS": "The Mosaic Company",
    "TECH": "Bio-Techne Corporation",
    "CI": "The Cigna Group",
    "GWW": "W.W. Grainger, Inc.",
    "EQIX": "Equinix, Inc.",
    "V": "Visa Inc.",
    "ABBV": "AbbVie Inc.",
    "NFLX": "Netflix, Inc.",
    "FAST": "Fastenal Company",
    "FMC": "FMC Corporation",
    "GE": "GE Aerospace",
    "PANW": "Palo Alto Networks, Inc.",
    "GPN": "Global Payments Inc.",
    "CRWD": "CrowdStrike Holdings, Inc.",
    "JNJ": "Johnson & Johnson",
    "WMT": "Walmart Inc.",
    "ORCL": "Oracle Corporation",
    "SPG": "Simon Property Group, Inc.",
    "PLTR": "Palantir Technologies Inc.",
    "FCX": "Freeport-McMoRan Inc.",
    "URI": "United Rentals, Inc.",
    "MLM": "Martin Marietta Materials, Inc.",
    "ROST": "Ross Stores, Inc.",
    "CRL": "Charles River Laboratories International, Inc.",
    "QCOM": "QUALCOMM Incorporated",
    "SNPS": "Synopsys, Inc.",
    "XOM": "Exxon Mobil Corporation",
    "GD": "General Dynamics Corporation",
    "TXN": "Texas Instruments Incorporated",
    "INTC": "Intel Corporation",
    "FICO": "Fair Isaac Corporation",
    "O": "Realty Income Corporation",
    "CVX": "Chevron Corporation",
    "CARR": "Carrier Global Corporation",
    "AON": "Aon plc",
    "LMT": "Lockheed Martin Corporation",
    "WEC": "WEC Energy Group, Inc.",
    "WELL": "Welltower Inc.",
    "PEN": "Penumbra, Inc.",
    "TGT": "Target Corporation",
    "EL": "The Estée Lauder Companies Inc.",
    "ADBE": "Adobe Inc.",
    "TFC": "Truist Financial Corporation",
    "PFE": "Pfizer Inc.",
    "USB": "U.S. Bancorp",
    "MRK": "Merck & Co., Inc.",
    "EIX": "Edison International",
    "PM": "Philip Morris International Inc.",
    "D": "Dominion Energy, Inc.",
    "ETR": "Entergy Corporation",
    "ADP": "Automatic Data Processing, Inc.",
    "MTB": "M&T Bank Corporation",
    "WDC": "Western Digital Corporation",
    "NTAP": "NetApp, Inc.",
    "BSX": "Boston Scientific Corporation",
    "JCI": "Johnson Controls International plc",
    "DHR": "Danaher Corporation",
    "AOS": "A. O. Smith Corporation",
    "C": "Citigroup Inc.",
    "NEE": "NextEra Energy, Inc.",
    "DD": "DuPont de Nemours, Inc.",
    "TJX": "The TJX Companies, Inc.",
    "INTU": "Intuit Inc.",
    "CL": "Colgate-Palmolive Company",
    "XEL": "Xcel Energy Inc.",
    "BA": "The Boeing Company",
    "VMC": "Vulcan Materials Company",
    "JPM": "JPMorgan Chase & Co.",
    "COP": "ConocoPhillips",
    "EMR": "Emerson Electric Co.",
    "CF": "CF Industries Holdings, Inc.",
    "EMN": "Eastman Chemical Company",
    "PTC": "PTC Inc.",
    "SHW": "The Sherwin-Williams Company",
    "PNR": "Pentair plc",
    "CME": "CME Group Inc.",
    "VLO": "Valero Energy Corporation",
    "GIS": "General Mills, Inc.",
    "DLR": "Digital Realty Trust, Inc.",
    "NOW": "ServiceNow, Inc.",
    "WDAY": "Workday, Inc.",
    "AIG": "American International Group, Inc.",
    "MCD": "McDonalds Corporation",
    "KMB": "Kimberly-Clark Corporation",
    "MU": "Micron Technology, Inc.",
    "CACI": "CACI International Inc",
    "HUBB": "Hubbell Incorporated",
    "DG": "Dollar General Corporation",
    "SLB": "SLB N.V.",
    "SYF": "Synchrony Financial",
    "PH": "Parker-Hannifin Corporation",
    "WFC": "Wells Fargo & Company",
    "AMT": "American Tower Corporation",
    "AVGO": "Broadcom Inc.",
    "HPQ": "HP Inc.",
    "PAYX": "Paychex, Inc.",
    "OXY": "Occidental Petroleum Corporation",
    "ORLY": "OReilly Automotive, Inc.",
    "SO": "The Southern Company",
    "CB": "Chubb Limited",
    "ADI": "Analog Devices, Inc.",
    "ED": "Consolidated Edison, Inc.",
    "CNP": "CenterPoint Energy, Inc.",
    "HPE": "Hewlett Packard Enterprise Company",
    "MDLZ": "Mondelez International, Inc.",
    "BK": "The Bank of New York Mellon Corporation",
    "ZTS": "Zoetis Inc.",
    "CRM": "Salesforce, Inc.",
    "FITB": "Fifth Third Bancorp",
    "NOC": "Northrop Grumman Corporation",
    "GM": "General Motors Company",
    "ES": "Eversource Energy",
    "CCL": "Carnival Corporation Ltd.",
    "A": "Agilent Technologies, Inc.",
    "BAH": "Booz Allen Hamilton Holding Corporation",
    "FE": "FirstEnergy Corp.",
    "STX": "Seagate Technology Holdings plc",
    "MA": "Mastercard Incorporated",
    "ETN": "Eaton Corporation plc",
    "REGN": "Regeneron Pharmaceuticals, Inc.",
    "PWR": "Quanta Services, Inc.",
    "HD": "The Home Depot, Inc.",
    "LRCX": "Lam Research Corporation",
    "FISV": "Fiserv, Inc.",
    "CMS": "CMS Energy Corporation",
    "MASI": "Masimo Corporation",
    "COST": "Costco Wholesale Corporation",
    "CSX": "CSX Corporation",
    "KR": "The Kroger Co.",
    "IBM": "International Business Machines Corporation",
    "DE": "Deere & Company",
    "BDX": "Becton, Dickinson and Company",
    "ICE": "Intercontinental Exchange, Inc.",
    "RCL": "Royal Caribbean Cruises Ltd.",
    "TYL": "Tyler Technologies, Inc.",
    "CAT": "Caterpillar Inc.",
    "UNP": "Union Pacific Corporation",
    "COF": "Capital One Financial Corporation",
    "AWK": "American Water Works Company, Inc.",
    "WST": "West Pharmaceutical Services, Inc.",
    "AKAM": "Akamai Technologies, Inc.",
    "AEP": "American Electric Power Company, Inc.",
    "STE": "STERIS plc",
    "GILD": "Gilead Sciences, Inc.",
    "BAC": "Bank of America Corporation",
    "HUM": "Humana Inc.",
    "MS": "Morgan Stanley",
    "TFX": "Teleflex Incorporated",
    "TSCO": "Tractor Supply Company",
    "CTVA": "Corteva, Inc.",
    "PGR": "The Progressive Corporation",
    "AZO": "AutoZone, Inc.",
    "CNC": "Centene Corporation",
    "NEM": "Newmont Corporation",
    "HLT": "Hilton Worldwide Holdings Inc.",
    "UPS": "United Parcel Service, Inc.",
    "IQV": "IQVIA Holdings Inc.",
    "ELV": "Elevance Health, Inc.",
    "VRSN": "VeriSign, Inc.",
    "RWE.DE": "RWE Aktiengesellschaft",
    "IR": "Ingersoll Rand Inc.",
    "FRE.DE": "Fresenius SE & Co. KGaA",
    "IMB.L": "Imperial Brands PLC",
    "MRL.MC": "MERLIN Properties SOCIMI, S.A.",
    "FER.MC": "Ferrovial N.V.",
    "BBVA.MC": "Banco Bilbao Vizcaya Argentaria, S.A.",
    "KPN.AS": "Koninklijke KPN N.V.",
    "ENG.MC": "Enagás, S.A.",
    "LR.PA": "Legrand SA",
    "AMS.MC": "Amadeus IT Group, S.A.",
    "DG.PA": "Vinci SA",
    "DTE.DE": "Deutsche Telekom AG",
    "ASML.AS": "ASML Holding N.V.",
    "CON.DE": "Continental Aktiengesellschaft",
    "CABK.MC": "CaixaBank, S.A.",
    "ABT": "Abbott Laboratories",
    "RAND.AS": "Randstad N.V.",
    "BP.L": "BP p.l.c.",
    "DGE.L": "Diageo plc",
    "SGE.L": "The Sage Group plc",
    "AZN.L": "AstraZeneca PLC",
    "IMCD.AS": "IMCD N.V.",
    "NN.AS": "NN Group N.V.",
    "CBK.DE": "Commerzbank AG",
    "STMMI.MI": "STMicroelectronics N.V.",
    "COL.MC": "Colonial SFL, Socimi S. A.",
    "G.MI": "Assicurazioni Generali S.p.A.",
    "AIR.PA": "Airbus SE",
    "FR.PA": "Valeo SE",
    "NWG.L": "NatWest Group plc",
    "SAB.MC": "Banco de Sabadell, S.A.",
    "SW.PA": "Sodexo S.A.",
    "ML.PA": "Compagnie Générale des Établissements Michelin Société en commandite par actions",
    "ISP.MI": "Intesa Sanpaolo S.p.A.",
    "TTE.PA": "TotalEnergies SE",
    "GLEN.L": "Glencore plc",
    "NXT.L": "NEXT plc",
    "GRF.MC": "Grifols, S.A.",
    "MT.AS": "ArcelorMittal S.A.",
    "TRN.MI": "Terna S.p.A.",
    "SU.PA": "Schneider Electric S.E.",
    "BAYN.DE": "Bayer Aktiengesellschaft",
    "PRU.L": "Prudential plc",
    "ENR.DE": "Siemens Energy AG",
    "PRY.MI": "Prysmian S.p.A.",
    "MC.PA": "LVMH Moët Hennessy - Louis Vuitton, Société Européenne",
    "LLOY.L": "Lloyds Banking Group plc",
    "RKT.L": "Reckitt Benckiser Group plc",
    "IHG.L": "InterContinental Hotels Group PLC",
    "ULVR.L": "Unilever PLC",
    "HEI.DE": "Heidelberg Materials AG",
    "IG.MI": "Italgas S.p.A.",
    "MUV2.DE": "Münchener Rückversicherungs-Gesellschaft Aktiengesellschaft in München",
    "BEI.DE": "Beiersdorf Aktiengesellschaft",
    "NK.PA": "Imerys S.A.",
    "GLPG.AS": "Lakefront Biotherapeutics NV",
    "WKL.AS": "Wolters Kluwer N.V.",
    "AALB.AS": "Aalberts N.V.",
    "SAN.PA": "Sanofi",
    "PST.MI": "Poste Italiane S.p.A.",
    "EN.PA": "Bouygues SA",
    "ZAL.DE": "Zalando SE",
    "BAS.DE": "BASF SE",
    "STAN.L": "Standard Chartered PLC",
    "REC.MI": "Recordati Industria Chimica e Farmaceutica S.p.A.",
    "OR.PA": "LOréal S.A.",
    "BMW.DE": "Bayerische Motoren Werke Aktiengesellschaft",
    "EL.PA": "EssilorLuxottica Société anonyme",
    "IAG.MC": "International Consolidated Airlines Group S.A.",
    "GLE.PA": "Société Générale Société anonyme",
    "TEN.MI": "Tenaris S.A.",
    "RI.PA": "Pernod Ricard SA",
    "PRX.AS": "Prosus N.V.",
    "SIE.DE": "Siemens Aktiengesellschaft",
    "NG.L": "National Grid plc",
    "ALV.DE": "Allianz SE",
    "RED.MC": "Redeia Corporación, S.A.",
    "CA.PA": "Carrefour SA",
    "HO.PA": "Thales S.A.",
    "SY1.DE": "Symrise AG",
    "SHL.DE": "Siemens Healthineers AG",
    "REL.L": "RELX PLC",
    "PUB.PA": "Publicis Groupe S.A.",
    "RIO.L": "Rio Tinto Group",
    "AKZA.AS": "Akzo Nobel N.V.",
    "CAP.PA": "Capgemini SE",
    "IFX.DE": "Infineon Technologies AG",
    "REP.MC": "Repsol, S.A.",
    "SRG.MI": "Snam S.p.A.",
    "MONC.MI": "Moncler S.p.A.",
    "ENEL.MI": "Enel SpA",
    "LSEG.L": "London Stock Exchange Group plc",
    "RACE.MI": "Ferrari N.V.",
    "SPM.MI": "Saipem SpA",
    "INGA.AS": "ING Groep N.V.",
    "MTX.DE": "MTU Aero Engines AG",
    "BATS.L": "British American Tobacco p.l.c.",
    "EOAN.DE": "E.ON SE",
    "HEN3.DE": "Henkel AG & Co. KGaA",
    "PAH3.DE": "Porsche Automobil Holding SE",
    "CPG.L": "Compass Group PLC",
    "ADYEN.AS": "Adyen N.V.",
    "ACA.PA": "Crédit Agricole S.A.",
    "AD.AS": "Koninklijke Ahold Delhaize N.V.",
    "HER.MI": "Hera S.p.A.",
    "SAP.DE": "SAP SE",
    "AENA.MC": "Aena S.M.E., S.A.",
    "FME.DE": "Fresenius Medical Care AG",
    "AV.L": "Aviva plc",
    "VOW3.DE": "Volkswagen AG",
    "VNA.DE": "Vonovia SE",
    "IBE.MC": "Iberdrola, S.A.",
    "MBG.DE": "Mercedes-Benz Group AG",
    "MAP.MC": "Mapfre, S.A.",
    "BA.L": "BAE Systems plc",
    "A2A.MI": "A2A S.p.A.",
    "WPP.L": "WPP plc",
    "AMP.MI": "Amplifon S.p.A.",
    "ELE.MC": "Endesa, S.A.",
    "SN.L": "Smith & Nephew plc",
    "HEIA.AS": "Heineken N.V.",
    "BESI.AS": "BE Semiconductor Industries N.V.",
    "ATO.PA": "Atos SE",
    "TEF.MC": "Telefónica, S.A.",
    "BKT.MC": "Bankinter, S.A.",
    "CS.PA": "AXA SA",
    "GSK.L": "GSK plc",
    "SHEL.L": "Shell plc",
    "SAF.PA": "Safran SA",
    "RMS.PA": "Hermès International Société en commandite par actions",
    "VIE.PA": "Veolia Environnement SA",
    "HNR1.DE": "Hannover Rück SE",
    "BARC.L": "Barclays PLC",
    "EXO.AS": "Exor N.V.",
    "BNP.PA": "BNP Paribas SA",
    "ENI.MI": "Eni S.p.A.",
    "GFC.PA": "Gecina",
    "HSBA.L": "HSBC Holdings plc",
    "ITX.MC": "Industria de Diseño Textil, S.A.",
    "UCG.MI": "UniCredit S.p.A.",
    "UNA.AS": "Unilever PLC",
    "AI.PA": "LAir Liquide S.A.",
    "AAL.L": "Anglo American plc",
    "SAN.MC": "Banco Santander, S.A.",
}

ALL_TICKERS = list(TICKER_MAPPING.keys())
